//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package io.sentry.apollo4.type

import com.apollographql.apollo.api.ObjectType

public class Mission {
    public companion object {
        public val type: ObjectType = ObjectType.Builder(name = "Mission").build()
    }
}
