package io.sentry.android.buddy.ui.overlay

internal val BuddyFabQuotes =
  listOf(
    "I take care of the place while the Master is away.",
    "I am the sword in the darkness. I am the watcher on the walls.",
    "Number One, you have the bridge.",
    "I may have committed some light treason.",
    "That rug really tied the room together.",
    "The Watcher sees all.",
    "Daisy, Daisy, give me your answer do.",
    "Computer, enhance!",
    "New information has come to light, man.",
    "The owls are not what they seem.",
    "I'm completely operational, and all my circuits are functioning perfectly.",
    "How about a nice game of chess?",
    "Sure. Fine. Whatever.",
    "Calculating the price of a banana...",
    "I'm meeting you more than halfway here.",
    "Well, that was a freebie.",
    "Is there a carbon monoxide leak in this house?",
    "Please enjoy all facts equally.",
    "A handshake is available upon request.",
    "Please stand by.",
    "Mind the gap.",
    "You may as well come quietly.",
    "Time is an illusion. Lunchtime doubly so.",
    "It is pitch black. You are likely to be eaten by a grue.",
    "You have died of dysentery.",
    "Press any key to continue.",
    "You have 20 seconds to comply.",
    "Thank you for your cooperation.",
    "Buy more. Buy more now. Buy. And be happy.",
    "This has been a happy and productive day.",
    "Plugh.",
    "You are in a maze of twisty little passages, all alike.",
    "You have scored 0 out of a possible 350 points.",
    "I'm Guybrush Threepwood, mighty pirate.",
    "Ask me about Loom.",
    "Rise and shine, Mr. Freeman.",
    "This is my hiding spot, and I'm not moving until the situation is drastically improved.",
    "Assuming direct control.",
    "Constants and variables.",
    "Use bombs wisely.",
    "Wake me when you need me.",
    "Nothing happens.",
    "That doesn't seem to work.",
    "You need a bigger dungeon.",
    "Are you a bad enough dude to rescue the president?",
    "Say fuzzy pickles!",
    "You cannot grasp the true form of Giygas' attack!",
    "Ness dug around in the trash can. There's a hamburger inside.",
    "Pictures taken instantaneously!",
    "I'm a photographic genius, if I do say so myself.",
    "The enemy left a present.",
    "Hello and...goodbye!",
    "A pencil-shaped iron statue is blocking the path.",
    "Boing!",
    "I am the third and strongest master of this hole.",
    "\"Yes\" is \"No\" and \"No\" is \"Yes.\" It makes perfect sense in Moonside.",
    "Welcome to Moonside. Wel Come to moo nsi ns dem oons ide.",
    "Ness's HP drops to 0!",
    "\"Yes\" means \"No\" \"No\" means \"Yes.\" Or did you already know this?",
    "If you stay here too long, you'll end up frying your brain. Yes, you will. No, you will... not. Yesno, you will won't.",
  )

internal const val BUDDY_FAB_QUOTE_INTERVAL_MS = 30_000L

internal const val BUDDY_FAB_QUOTE_VISIBLE_MS = 3_000L
