# This is used by the action https://github.com/dorny/paths-filter

high_risk_code: &high_risk_code
  # Transport classes
  - "sentry/src/main/java/io/sentry/transport/AsyncHttpTransport.java"
  - "sentry/src/main/java/io/sentry/transport/HttpConnection.java"
  - "sentry/src/main/java/io/sentry/transport/QueuedThreadPoolExecutor.java"
  - "sentry/src/main/java/io/sentry/transport/RateLimiter.java"
  - "sentry-apache-http-client-5/src/main/java/io/sentry/transport/apache/ApacheHttpClientTransport.java"

  # Class used by hybrid SDKs
  - "sentry-android-core/src/main/java/io/sentry/android/core/InternalSentrySdk.java"

config_kt:
  - "buildSrc/src/main/java/Config.kt"

sdk_name_check_scripts:
  - ".github/workflows/sdk-name-check.yml"
  - "scripts/detect_sdk_name_changes.py"
  - "scripts/test_detect_sdk_name_changes.py"
