minVersion: 0.29.3
changelogPolicy: auto
targets:
  - name: maven
    includeNames: /^sentry.*$/
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh-staging-api
    mavenRepoUrl: https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/
    android:
      distDirRegex: /^(sentry-android-|.*-android).*$/
      fileReplaceeRegex: /\d+\.\d+\.\d+(-\w+(\.\d+)?)?(-SNAPSHOT)?/
      fileReplacerStr: release.aar
  - name: github
    excludeNames: /^libsentry.*\.so$/
  - name: registry
    sdks:
      maven:io.sentry:sentry:
      maven:io.sentry:sentry-spring:
      maven:io.sentry:sentry-spring-jakarta:
      maven:io.sentry:sentry-spring-7:
      maven:io.sentry:sentry-spring-boot:
      maven:io.sentry:sentry-spring-boot-jakarta:
      maven:io.sentry:sentry-spring-boot-starter:
      maven:io.sentry:sentry-spring-boot-starter-jakarta:
      maven:io.sentry:sentry-spring-boot-4:
      maven:io.sentry:sentry-spring-boot-4-starter:
      maven:io.sentry:sentry-servlet:
      maven:io.sentry:sentry-servlet-jakarta:
      maven:io.sentry:sentry-logback:
      maven:io.sentry:sentry-log4j2:
      maven:io.sentry:sentry-jul:
      maven:io.sentry:sentry-apache-http-client-5:
      maven:io.sentry:sentry-android:
      maven:io.sentry:sentry-android-core:
      maven:io.sentry:sentry-android-distribution:
      maven:io.sentry:sentry-android-ndk:
      maven:io.sentry:sentry-android-timber:
      maven:io.sentry:sentry-kotlin-extensions:
      maven:io.sentry:sentry-android-fragment:
      maven:io.sentry:sentry-bom:
      maven:io.sentry:sentry-openfeign:
      maven:io.sentry:sentry-opentelemetry-agent:
      maven:io.sentry:sentry-opentelemetry-agentcustomization:
      maven:io.sentry:sentry-opentelemetry-agentless:
      maven:io.sentry:sentry-opentelemetry-agentless-spring:
      maven:io.sentry:sentry-opentelemetry-bootstrap:
      maven:io.sentry:sentry-opentelemetry-core:
      maven:io.sentry:sentry-apollo:
      maven:io.sentry:sentry-jdbc:
      maven:io.sentry:sentry-graphql:
      maven:io.sentry:sentry-graphql-22:
      maven:io.sentry:sentry-graphql-core:
      maven:io.sentry:sentry-quartz:
      maven:io.sentry:sentry-okhttp:
      maven:io.sentry:sentry-android-navigation:
      maven:io.sentry:sentry-compose:
      maven:io.sentry:sentry-compose-android:
      maven:io.sentry:sentry-compose-desktop:
      maven:io.sentry:sentry-apollo-3:
      maven:io.sentry:sentry-android-sqlite:
      maven:io.sentry:sentry-android-replay:
      maven:io.sentry:sentry-apollo-4:
      maven:io.sentry:sentry-reactor:
      maven:io.sentry:sentry-ktor-client:
      maven:io.sentry:sentry-async-profiler:
