minVersion: 0.23.1
changelogPolicy: auto
targets:
  - name: github
  - name: registry
    sdks:
      maven:io.sentry:sentry:
      maven:io.sentry:sentry-spring:
      maven:io.sentry:sentry-spring-boot-starter:
      maven:io.sentry:sentry-servlet:
      maven:io.sentry:sentry-logback:
      maven:io.sentry:sentry-log4j2:
      maven:io.sentry:sentry-jul:
      maven:io.sentry:sentry-apache-http-client-5:
      maven:io.sentry:sentry-android:
      maven:io.sentry:sentry-android-core:
      maven:io.sentry:sentry-android-ndk:
      maven:io.sentry:sentry-android-timber:
      maven:io.sentry:sentry-android-okhttp:
      maven:io.sentry:sentry-kotlin-extensions:
      maven:io:sentry:sentry-android-fragment:
  - name: maven
    gradleCliPath: ./gradlew
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh
    mavenRepoUrl: https://oss.sonatype.org/service/local/staging/deploy/maven2/
    android:
      distDirRegex: /^sentry-android-.*$/
      fileReplaceeRegex: /\d\.\d\.\d(-SNAPSHOT)?/
      fileReplacerStr: release.aar
