comment: no
codecov:
  require_ci_to_pass: no
  max_report_age: off

coverage:
  status:
    project:
      default:
        target: 78%
        threshold: 4%
    patch: off
  range: 78...100
  precision: 3
  round: down

ignore:
  - "**/src/test/*"
  - "sentry-android-integration-tests/*"
  - "sentry-system-test-support/*"
  - "sentry-test-support/*"
  - "sentry-samples/*"
  - "sentry-async-profiler/src/main/java/io/sentry/asyncprofiler/vendor/asyncprofiler/**"
