//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package io.sentry.apollo3.type

import com.apollographql.apollo3.api.ObjectType

public class Mission {
  public companion object {
    public val type: ObjectType = ObjectType(name = "Mission")
  }
}
