package io.sentry.samples.android.navigation

import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import java.util.Locale
import kotlin.math.roundToInt

/**
 * Bottom sheet for displaying the last [TRANSACTION_HISTORY_LIMIT] transactions generated by the
 * Sentry SDK.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun Nav2TransactionHistorySheet(
  transactions: List<Nav2TransactionTrace>,
  showActivityUiLoadTransactionDelayMessage: Boolean,
  onDismissRequest: () -> Unit,
  onOpenTransaction: (String) -> Unit,
  onDumpTransactionUrl: (String) -> Unit,
  onCopyTransactionUrl: (String) -> Unit,
) {
  ModalBottomSheet(onDismissRequest = onDismissRequest) {
    Column(
      modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp).padding(bottom = 24.dp),
      verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      Text(
        "Recent transactions",
        style = MaterialTheme.typography.headlineSmall,
        fontWeight = FontWeight.Bold,
      )
      Text(
        "Newest first. Open a few Nav2 routes, then return here to inspect the last 10 transactions emitted by the SDK.",
        style = MaterialTheme.typography.bodyMedium,
      )
      Column(
        modifier = Modifier.fillMaxWidth().verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(12.dp),
      ) {
        if (transactions.isEmpty()) {
          EmptyTransactionHistory(showActivityUiLoadTransactionDelayMessage)
        } else {
          transactions.forEach { transaction ->
            TransactionCard(
              transaction = transaction,
              onOpenTransaction = onOpenTransaction,
              onDumpTransactionUrl = onDumpTransactionUrl,
              onCopyTransactionUrl = onCopyTransactionUrl,
            )
          }
        }
      }
    }
  }
}

@Composable
private fun EmptyTransactionHistory(showActivityUiLoadTransactionDelayMessage: Boolean) {
  Card(
    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
    modifier = Modifier.fillMaxWidth(),
  ) {
    Text(
      if (showActivityUiLoadTransactionDelayMessage) {
        ACTIVITY_UI_LOAD_EMPTY_HISTORY_MESSAGE
      } else {
        EMPTY_HISTORY_MESSAGE
      },
      modifier = Modifier.padding(16.dp),
      style = MaterialTheme.typography.bodyMedium,
    )
  }
}

@Composable
private fun TransactionCard(
  transaction: Nav2TransactionTrace,
  onOpenTransaction: (String) -> Unit,
  onDumpTransactionUrl: (String) -> Unit,
  onCopyTransactionUrl: (String) -> Unit,
) {
  Card(
    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant),
    modifier = Modifier.fillMaxWidth(),
  ) {
    Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
      Row(verticalAlignment = Alignment.CenterVertically) {
        Column(modifier = Modifier.weight(1f)) {
          Text(
            transaction.name,
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
          )
          Text(
            listOfNotNull(transaction.operation, transaction.status).joinToString(" - "),
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
        }
        Text(
          "Tab: ${transaction.tab}",
          style = MaterialTheme.typography.labelLarge,
          fontFamily = FontFamily.Monospace,
        )
      }

      TransactionWaterfall(transaction)

      if (transaction.sentryUrl == null) {
        Text(
          "Sentry URL unavailable for this DSN.",
          style = MaterialTheme.typography.bodySmall,
          color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
      } else {
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
          TextButton(onClick = { onOpenTransaction(transaction.sentryUrl) }) {
            Text("Open in Sentry")
          }
          TextButton(onClick = { onDumpTransactionUrl(transaction.sentryUrl) }) {
            Text("Dump URL")
          }
          TextButton(onClick = { onCopyTransactionUrl(transaction.sentryUrl) }) {
            Text("Copy URL")
          }
        }
      }
    }
  }
}

@Composable
private fun TransactionWaterfall(transaction: Nav2TransactionTrace) {
  val rows = transaction.spans.flattenTraceRows()
  val scrollState = rememberScrollState()
  Column(modifier = Modifier.horizontalScroll(scrollState)) {
    TimelineHeader(transaction.durationMillis)
    TraceRow(
      label = transaction.name,
      operation = transaction.operation,
      level = 0,
      startOffsetMillis = 0.0,
      durationMillis = transaction.durationMillis,
      totalDurationMillis = transaction.durationMillis,
      color = ROOT_SPAN_COLOR,
      showBranch = false,
    )
    rows.forEachIndexed { index, row ->
      TraceRow(
        label = row.span.description ?: row.span.operation,
        operation = row.span.operation,
        level = row.level,
        startOffsetMillis = row.span.startOffsetMillis,
        durationMillis = row.span.durationMillis,
        totalDurationMillis = transaction.durationMillis,
        color = spanBarColor(index, row.span.operation),
        showBranch = true,
      )
    }
  }
}

@Composable
private fun TimelineHeader(totalDurationMillis: Double) {
  Row(modifier = Modifier.width(WATERFALL_WIDTH).height(28.dp)) {
    Spacer(Modifier.width(LABEL_WIDTH))
    Row(
      modifier = Modifier.width(TIMELINE_WIDTH),
      horizontalArrangement = Arrangement.SpaceBetween,
    ) {
      listOf(0.0, 0.25, 0.5, 0.75, 1.0).forEach { fraction ->
        Text(
          (totalDurationMillis * fraction).formatMillis(),
          style = MaterialTheme.typography.labelSmall,
          fontFamily = FontFamily.Monospace,
          color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
      }
    }
  }
}

@Composable
private fun TraceRow(
  label: String,
  operation: String,
  level: Int,
  startOffsetMillis: Double,
  durationMillis: Double,
  totalDurationMillis: Double,
  color: Color,
  showBranch: Boolean,
) {
  Row(
    modifier = Modifier.width(WATERFALL_WIDTH).height(34.dp),
    verticalAlignment = Alignment.CenterVertically,
  ) {
    Row(
      modifier = Modifier.width(LABEL_WIDTH).padding(end = 12.dp),
      verticalAlignment = Alignment.CenterVertically,
    ) {
      Spacer(Modifier.width((level * 16).dp))
      if (showBranch) {
        Text("|-", color = MaterialTheme.colorScheme.outline)
        Spacer(Modifier.width(4.dp))
      }
      Text(
        "$operation - $label",
        style = MaterialTheme.typography.bodySmall,
        fontWeight = if (level == 0) FontWeight.Bold else FontWeight.Normal,
        maxLines = 1,
        overflow = TextOverflow.Ellipsis,
      )
    }
    BoxWithConstraints(modifier = Modifier.width(TIMELINE_WIDTH).height(24.dp)) {
      val safeTotalDuration = totalDurationMillis.coerceAtLeast(1.0)
      val startFraction = (startOffsetMillis / safeTotalDuration).coerceIn(0.0, 1.0).toFloat()
      val widthFraction = (durationMillis / safeTotalDuration).coerceIn(0.0, 1.0).toFloat()
      val barX = maxWidth * startFraction
      val barWidth = (maxWidth * widthFraction).coerceAtLeast(3.dp).coerceAtMost(maxWidth - barX)

      TimelineGrid()
      Box(
        modifier =
          Modifier.offset(x = barX)
            .width(barWidth)
            .height(12.dp)
            .align(Alignment.CenterStart)
            .clip(RoundedCornerShape(2.dp))
            .background(color)
      )
      Text(
        durationMillis.formatMillis(),
        modifier = Modifier.offset(x = barX + barWidth + 4.dp).align(Alignment.CenterStart),
        style = MaterialTheme.typography.labelSmall,
        fontFamily = FontFamily.Monospace,
        color = MaterialTheme.colorScheme.onSurfaceVariant,
        maxLines = 1,
      )
    }
  }
}

@Composable
private fun TimelineGrid() {
  Row(modifier = Modifier.width(TIMELINE_WIDTH).height(24.dp)) {
    repeat(4) {
      Box(modifier = Modifier.weight(1f).height(24.dp)) {
        Box(
          modifier =
            Modifier.width(1.dp)
              .height(24.dp)
              .align(Alignment.CenterEnd)
              .background(MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.45f))
        )
      }
    }
  }
}

private fun List<Nav2TraceSpan>.flattenTraceRows(level: Int = 1): List<TraceRowData> =
  flatMap { span ->
    listOf(TraceRowData(span = span, level = level)) + span.children.flattenTraceRows(level + 1)
  }

private fun spanBarColor(index: Int, operation: String): Color =
  when {
    operation.startsWith("ui.compose") -> COMPOSE_SPAN_COLOR
    operation.startsWith("ui.render") -> RENDER_SPAN_COLOR
    operation.startsWith("http") -> HTTP_SPAN_COLOR
    else -> CHILD_SPAN_COLORS[index % CHILD_SPAN_COLORS.size]
  }

private fun Double.formatMillis(): String =
  when {
    this < 10.0 -> String.format(Locale.ROOT, "%.2fms", this)
    this < 100.0 -> String.format(Locale.ROOT, "%.1fms", this)
    else -> "${roundToInt()}ms"
  }

private data class TraceRowData(val span: Nav2TraceSpan, val level: Int)

private const val EMPTY_HISTORY_MESSAGE = "No transactions have been emitted yet."
private const val ACTIVITY_UI_LOAD_EMPTY_HISTORY_MESSAGE =
  "No transactions have been emitted yet. ui.load transactions can take up to 30 seconds to " +
    "appear after the last span is produced."
private val ROOT_SPAN_COLOR = Color(0xFFE95F5C)
private val COMPOSE_SPAN_COLOR = Color(0xFF5B3DB6)
private val RENDER_SPAN_COLOR = Color(0xFFBBD233)
private val HTTP_SPAN_COLOR = Color(0xFF2F80ED)
private val CHILD_SPAN_COLORS =
  listOf(Color(0xFF7553D6), Color(0xFF9B51E0), Color(0xFF27AE60), Color(0xFFF2C94C))

private val LABEL_WIDTH = 260.dp
private val TIMELINE_WIDTH = 420.dp
private val WATERFALL_WIDTH = LABEL_WIDTH + TIMELINE_WIDTH
