//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package com.example.rocketreserver.adapter

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.StringAdapter
import com.apollographql.apollo3.api.json.JsonReader
import com.apollographql.apollo3.api.json.JsonWriter
import io.sentry.apollo3.LaunchDetailsQuery
import kotlin.IllegalStateException

public object LaunchDetailsQuery_VariablesAdapter : Adapter<LaunchDetailsQuery> {
    public override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters):
        LaunchDetailsQuery = throw IllegalStateException("Input type used in output position")

    public override fun toJson(
        writer: JsonWriter,
        customScalarAdapters: CustomScalarAdapters,
        `value`: LaunchDetailsQuery,
    ) {
        writer.name("id")
        StringAdapter.toJson(writer, customScalarAdapters, value.id)
    }
}
