//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.3.0'.
//
package io.sentry.apollo4.selections

import com.apollographql.apollo.api.*
import io.sentry.apollo4.type.GraphQLID
import io.sentry.apollo4.type.GraphQLString
import io.sentry.apollo4.type.Launch
import io.sentry.apollo4.type.Mission
import io.sentry.apollo4.type.Query.Companion.type
import io.sentry.apollo4.type.Rocket
import kotlin.collections.List

public object LaunchDetailsQuerySelections {
    private val mission: List<CompiledSelection> = listOf(
        CompiledField.Builder(
            name = "name",
            type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
            name = "missionPatch",
            type = GraphQLString.type
        ).arguments(
            listOf(
                CompiledArgument.Builder(CompiledArgumentDefinition.Builder("size").build()).value("LARGE").build()
            )
        )
            .build()
    )

    private val rocket: List<CompiledSelection> = listOf(
        CompiledField.Builder(
            name = "name",
            type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
            name = "type",
            type = GraphQLString.type
        ).build()
    )

    private val launch: List<CompiledSelection> = listOf(
        CompiledField.Builder(
            name = "id",
            type = GraphQLID.type.notNull()
        ).build(),
        CompiledField.Builder(
            name = "site",
            type = GraphQLString.type
        ).build(),
        CompiledField.Builder(
            name = "mission",
            type = Mission.type
        ).selections(mission)
            .build(),
        CompiledField.Builder(
            name = "rocket",
            type = Rocket.type
        ).selections(rocket)
            .build()
    )

    public val root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
            name = "launch",
            type = Launch.type
        ).arguments(
            listOf(
                CompiledArgument.Builder(CompiledArgumentDefinition.Builder("id").build()).value("id").build()
            )
        )
            .selections(launch)
            .build()
    )
}
