name: Changelog Preview
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@70714dda896a3f5d5ad0a3e55b1d73a64ee7bf8f # v2
    secrets: inherit
