name: Enforce License Compliance

on:
  push:
    branches: [master, main, release/*]
  pull_request:
    branches: [master, main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # TODO: remove this when upstream is fixed
      - name: Disable Gradle configuration cache (see https://github.com/fossas/fossa-cli/issues/872)
        run: sed -i 's/^org.gradle.configuration-cache=.*/org.gradle.configuration-cache=false/' gradle.properties

      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@48236a773346cb6552a7bda1ee370d2797365d87 # main
        with:
          skip_checkout: 'true'
          fossa_test_timeout_seconds: 3600
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
