name: Validate PR

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: getsentry/github-workflows/validate-pr@26f565c05d0dd49f703d238706b775883037d76b
        with:
          app-id: ${{ vars.SDK_MAINTAINER_BOT_APP_ID }}
          private-key: ${{ secrets.SDK_MAINTAINER_BOT_PRIVATE_KEY }}
