apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: Android benchmarks with Espresso
    tags:
      - benchmarks
      - android

defaults:
  timeout: 30m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk

suites:

  # Devices are chosen so that there is a high-end and a low-end device for each api level
  - name: "Android 12 (api 31)"
    devices:
      - id: Google_Pixel_6_Pro_real_us # Google Pixel 6 Pro - api 31 (12)
      - id: Google_Pixel_3_12_real_us # Google Pixel 3 - api 31 (12)
    testOptions:
      useTestOrchestrator: true

  - name: "Android 11 (api 30)"
    devices:
      - id: OnePlus_9_Pro_real_us # OnePlus 9 Pro - api 30 (11)
      - id: Google_Pixel_2_real_us # Google Pixel 2 - api 30 (11)
    testOptions:
      useTestOrchestrator: true

# Commenting for the moment, due to the error "Cannot install test-services-1.4.1.apk on device" on low Android versions
#  - name: "Android 5 (api 22)"
#    devices:
#      - id: Amazon_Kindle_Fire_HD_8_real_us # Amazon Kindle Fire HD 8 - api 22 (5.1.1)
#    testOptions:
#      useTestOrchestrator: true

#      - id: Google_Pixel_4_XL_real_us1 # Google Pixel 4 XL - api 29 (10)
#      - id: Motorola_Moto_G_Power_real_us # Motorola Moto G Power (2021) - api 29 (10)
#      - id: Samsung_Galaxy_S8_plus_real_us # Samsung Galaxy S8+ - api 28 (9)
#      - id: LG_G8_ThinQ_real_us # LG G8 ThinQ - api 28 (9)
#      - id: OnePlus_5_real_us # OnePlus 5 - api 27 (8.1.0)
#      - id: LG_K30_real_us1 # LG K30 - api 27 (8.1.0)
#      - id: HTC_10_real_us # HTC 10 - api 26 (8.0.0)
#      - id: Samsung_A3_real # Samsung Galaxy A3 2017 - api 26 (8.0.0)
#      - id: ZTE_Axon_7_real2_us # ZTE Axon 7 - api 25 (7.1.1)
#      - id: Motorola_Moto_X_Play_real # Motorola Moto X Play - api 25 (7.1.1)
#      - id: Samsung_note_5_real_us # Samsung Galaxy Note 5 - api 24 (7.0)
#      - id: LG_K10_real # LG K10 - api 24 (7.0)
#      - id: Samsung_Galaxy_S6_Edge_Plus_real # Samsung Galaxy S6 Edge+ - api 23 (6.0.1)
#      - id: Samsung_Tab_E_real_us # Samsung Tab E - api 23 (6.0.1)

artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
