apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: Android benchmarks with Espresso
    tags:
      - benchmarks
      - android

defaults:
  timeout: 30m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk

suites:

  # Devices are chosen so that there is a high-end and a low-end device for each api level
  - name: "Android 12 (api 31)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_6_Pro_real_us # Google Pixel 6 Pro - api 31 (12) - high end
      - id: Google_Pixel_5_12_real_us # Google Pixel 5 - api 31 (12) - low end

  - name: "Android 11 (api 30)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Samsung_Galaxy_S10_Plus_11_real_us # Samsung Galaxy S10+ - api 30 (11) - high end
      - id: Samsung_Galaxy_A71_5G_real_us # Samsung Galaxy A71 5G - api 30 (11) - mid end
      - id: Google_Pixel_3a_real # Google Pixel 3a - api 30 (11) - low end

  - name: "Android 10 (api 29)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_3a_XL_real # Google Pixel 3a XL - api 29 (10)
      - id: Nokia_7_1_real_us # Nokia 7.1 - api 29 (10)

# At the time of writing (July, 4, 2022), the market share per android version is:
# 12.0 = 17.54%, 11.0 = 31.65%, 10.0 = 21.92%
# Using these 3 versions we cover 71,11% of all devices out there. Currently, this is enough for benchmarking scope
# Leaving these devices here in case we change mind on them
#    devices:
#      - id: Samsung_Galaxy_S8_plus_real_us # Samsung Galaxy S8+ - api 28 (9)
#      - id: LG_G8_ThinQ_real_us # LG G8 ThinQ - api 28 (9)
#      - id: OnePlus_5_real_us # OnePlus 5 - api 27 (8.1.0)
#      - id: LG_K30_real_us1 # LG K30 - api 27 (8.1.0)
#      - id: HTC_10_real_us # HTC 10 - api 26 (8.0.0)
#      - id: Samsung_A3_real # Samsung Galaxy A3 2017 - api 26 (8.0.0)
#      - id: ZTE_Axon_7_real2_us # ZTE Axon 7 - api 25 (7.1.1)
#      - id: Motorola_Moto_X_Play_real # Motorola Moto X Play - api 25 (7.1.1)
#      - id: Samsung_note_5_real_us # Samsung Galaxy Note 5 - api 24 (7.0)
#      - id: LG_K10_real # LG K10 - api 24 (7.0)
#      - id: Samsung_Galaxy_S6_Edge_Plus_real # Samsung Galaxy S6 Edge+ - api 23 (6.0.1)
#      - id: Samsung_Tab_E_real_us # Samsung Tab E - api 23 (6.0.1)
#      - id: Amazon_Kindle_Fire_HD_8_real_us # Amazon Kindle Fire HD 8 - api 22 (5.1.1)

artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
