apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 1
  metadata:
    name: Android benchmarks with Espresso
    tags:
      - benchmarks
      - android
espresso:
  app: ./sentry-uitest/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-uitest/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk
suites:
  name: "Android Benchmarks"
  devices:
    - name: "Google Pixel 2"
      platformVersion: 11
    - id: Google_Pixel_2_real_us
  testOptions:
    useTestOrchestrator: true
# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
