apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 3
  metadata:
    build: sentry-uitest-android-benchmark-$GITHUB_REF-$GITHUB_SHA
    tags:
      - benchmarks
      - android

defaults:
  timeout: 90m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk

suites:

  # Devices are chosen so that there is a high-end and a low-end device for each api level
  - name: "Android 15 (api 35)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_9_Pro_XL_15_real_sjc1 # Google Pixel 9 Pro XL - api 35 (15) - high end
      - id: Samsung_Galaxy_S23_15_real_sjc1 # Samsung Galaxy S23 - api 35 (15) - mid end
      - id: Google_Pixel_6a_15_real_sjc1 # Google Pixel 6a - api 35 (15) - low end

  - name: "Android 14 (api 34)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_9_Pro_XL_real_sjc1 # Google Pixel 9 Pro XL - api 34 (14) - high end
      - id: Samsung_Galaxy_A54_real_sjc1 # Samsung Galaxy A54 - api 34 (14) - low end

  - name: "Android 13 (api 33)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_7_Pro_real_us # Google Pixel 7 Pro - api 33 (13) - high end
      - id: Samsung_Galaxy_A32_5G_real_sjc1 # Samsung Galaxy A32 5G - api 33 (13) - low end

# At the time of writing (August, 13, 2025), the market share per android version is:
# 15.0 = 26.75%, 14.0 = 19.5%, 13 = 15.95%
# Using these 3 versions we cover 62.2% of all devices out there. Currently, this is enough for benchmarking scope

artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
