apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 4
  metadata:
    build: sentry-uitest-android-ui-$GITHUB_REF-$GITHUB_SHA
    tags:
      - e2e
      - android

defaults:
  timeout: 45m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android/build/outputs/apk/release/sentry-uitest-android-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android/build/outputs/apk/androidTest/release/sentry-uitest-android-release-androidTest.apk
suites:

  - name: "Android 15 Ui test (api 35)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - name: ".*"
        platformVersion: "15"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
