apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 1
  metadata:
    build: sentry-uitest-android-benchmark-lite-$GITHUB_REF-$GITHUB_SHA
    tags:
      - benchmarks
      - android

defaults:
  timeout: 40m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk

suites:

  - name: "Android 11 (api 30)"
    testOptions:
      clearPackageData: true
      useTestOrchestrator: true
    devices:
      - id: Google_Pixel_3a_real # Google Pixel 3a - api 30 (11)

artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
