apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: Android benchmarks with Espresso
    tags:
      - benchmarks
      - android

defaults:
  timeout: 20m

espresso:
  app: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/release/sentry-uitest-android-benchmark-release.apk
  testApp: ./sentry-android-integration-tests/sentry-uitest-android-benchmark/build/outputs/apk/androidTest/release/sentry-uitest-android-benchmark-release-androidTest.apk

suites:

  - name: "Android 11 (api 30)"
    devices:
      - id: OnePlus_Nord_N200_5G_real_us # OnePlus Nord N200 5G - api 30 (11)

artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
